apiVersion: v1
kind: Namespace
metadata:
  name: world-repro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: victim
  name: victim
  namespace: world-repro
spec:
  replicas: 20
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victim-world-egress
  namespace: world-repro
spec:
  egress:
  - toCIDR:
    - 0.0.0.0/0
  endpointSelector:
    matchLabels:
      app: victim
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: noise-policy-cidr-allocator
  namespace: world-repro
spec:
  egress:
  - toCIDR:
    - 11.0.0.1/32
    - 11.0.1.1/32
    - 11.0.2.1/32
    - 11.0.3.1/32
    - 11.0.4.1/32
    - 11.0.5.1/32
    - 11.0.6.1/32
    - 11.0.7.1/32
    - 11.0.8.1/32
    - 11.0.9.1/32
    - 11.0.10.1/32
    - 11.0.11.1/32
    - 11.0.12.1/32
    - 11.0.13.1/32
    - 11.0.14.1/32
    - 11.0.15.1/32
    - 11.0.16.1/32
    - 11.0.17.1/32
    - 11.0.18.1/32
    - 11.0.19.1/32
    - 11.0.20.1/32
    - 11.0.21.1/32
    - 11.0.22.1/32
    - 11.0.23.1/32
    - 11.0.24.1/32
    - 11.0.25.1/32
    - 11.0.26.1/32
    - 11.0.27.1/32
    - 11.0.28.1/32
    - 11.0.29.1/32
    - 11.0.30.1/32
    - 11.0.31.1/32
    - 11.0.32.1/32
    - 11.0.33.1/32
    - 11.0.34.1/32
    - 11.0.35.1/32
    - 11.0.36.1/32
    - 11.0.37.1/32
    - 11.0.38.1/32
    - 11.0.39.1/32
    - 11.0.40.1/32
    - 11.0.41.1/32
    - 11.0.42.1/32
    - 11.0.43.1/32
    - 11.0.44.1/32
    - 11.0.45.1/32
    - 11.0.46.1/32
    - 11.0.47.1/32
    - 11.0.48.1/32
    - 11.0.49.1/32
    - 11.0.50.1/32
    - 11.0.51.1/32
    - 11.0.52.1/32
    - 11.0.53.1/32
    - 11.0.54.1/32
    - 11.0.55.1/32
    - 11.0.56.1/32
    - 11.0.57.1/32
    - 11.0.58.1/32
    - 11.0.59.1/32
    - 11.0.60.1/32
    - 11.0.61.1/32
    - 11.0.62.1/32
    - 11.0.63.1/32
    - 11.0.64.1/32
    - 11.0.65.1/32
    - 11.0.66.1/32
    - 11.0.67.1/32
    - 11.0.68.1/32
    - 11.0.69.1/32
    - 11.0.70.1/32
    - 11.0.71.1/32
    - 11.0.72.1/32
    - 11.0.73.1/32
    - 11.0.74.1/32
    - 11.0.75.1/32
    - 11.0.76.1/32
    - 11.0.77.1/32
    - 11.0.78.1/32
    - 11.0.79.1/32
    - 11.0.80.1/32
    - 11.0.81.1/32
    - 11.0.82.1/32
    - 11.0.83.1/32
    - 11.0.84.1/32
    - 11.0.85.1/32
    - 11.0.86.1/32
    - 11.0.87.1/32
    - 11.0.88.1/32
    - 11.0.89.1/32
    - 11.0.90.1/32
    - 11.0.91.1/32
    - 11.0.92.1/32
    - 11.0.93.1/32
    - 11.0.94.1/32
    - 11.0.95.1/32
    - 11.0.96.1/32
    - 11.0.97.1/32
    - 11.0.98.1/32
    - 11.0.99.1/32
    - 11.0.100.1/32
    - 11.0.101.1/32
    - 11.0.102.1/32
    - 11.0.103.1/32
    - 11.0.104.1/32
    - 11.0.105.1/32
    - 11.0.106.1/32
    - 11.0.107.1/32
    - 11.0.108.1/32
    - 11.0.109.1/32
    - 11.0.110.1/32
    - 11.0.111.1/32
    - 11.0.112.1/32
    - 11.0.113.1/32
    - 11.0.114.1/32
    - 11.0.115.1/32
    - 11.0.116.1/32
    - 11.0.117.1/32
    - 11.0.118.1/32
    - 11.0.119.1/32
    - 11.0.120.1/32
    - 11.0.121.1/32
    - 11.0.122.1/32
    - 11.0.123.1/32
    - 11.0.124.1/32
    - 11.0.125.1/32
    - 11.0.126.1/32
    - 11.0.127.1/32
    - 11.0.128.1/32
    - 11.0.129.1/32
    - 11.0.130.1/32
    - 11.0.131.1/32
    - 11.0.132.1/32
    - 11.0.133.1/32
    - 11.0.134.1/32
    - 11.0.135.1/32
    - 11.0.136.1/32
    - 11.0.137.1/32
    - 11.0.138.1/32
    - 11.0.139.1/32
    - 11.0.140.1/32
    - 11.0.141.1/32
    - 11.0.142.1/32
    - 11.0.143.1/32
    - 11.0.144.1/32
    - 11.0.145.1/32
    - 11.0.146.1/32
    - 11.0.147.1/32
    - 11.0.148.1/32
    - 11.0.149.1/32
    - 11.0.150.1/32
    - 11.0.151.1/32
    - 11.0.152.1/32
    - 11.0.153.1/32
    - 11.0.154.1/32
    - 11.0.155.1/32
    - 11.0.156.1/32
    - 11.0.157.1/32
    - 11.0.158.1/32
    - 11.0.159.1/32
    - 11.0.160.1/32
    - 11.0.161.1/32
    - 11.0.162.1/32
    - 11.0.163.1/32
    - 11.0.164.1/32
    - 11.0.165.1/32
    - 11.0.166.1/32
    - 11.0.167.1/32
    - 11.0.168.1/32
    - 11.0.169.1/32
    - 11.0.170.1/32
    - 11.0.171.1/32
    - 11.0.172.1/32
    - 11.0.173.1/32
    - 11.0.174.1/32
    - 11.0.175.1/32
    - 11.0.176.1/32
    - 11.0.177.1/32
    - 11.0.178.1/32
    - 11.0.179.1/32
    - 11.0.180.1/32
    - 11.0.181.1/32
    - 11.0.182.1/32
    - 11.0.183.1/32
    - 11.0.184.1/32
    - 11.0.185.1/32
    - 11.0.186.1/32
    - 11.0.187.1/32
    - 11.0.188.1/32
    - 11.0.189.1/32
    - 11.0.190.1/32
    - 11.0.191.1/32
    - 11.0.192.1/32
    - 11.0.193.1/32
    - 11.0.194.1/32
    - 11.0.195.1/32
    - 11.0.196.1/32
    - 11.0.197.1/32
    - 11.0.198.1/32
    - 11.0.199.1/32
    - 11.0.200.1/32
    - 11.0.201.1/32
    - 11.0.202.1/32
    - 11.0.203.1/32
    - 11.0.204.1/32
    - 11.0.205.1/32
    - 11.0.206.1/32
    - 11.0.207.1/32
    - 11.0.208.1/32
    - 11.0.209.1/32
    - 11.0.210.1/32
    - 11.0.211.1/32
    - 11.0.212.1/32
    - 11.0.213.1/32
    - 11.0.214.1/32
    - 11.0.215.1/32
    - 11.0.216.1/32
    - 11.0.217.1/32
    - 11.0.218.1/32
    - 11.0.219.1/32
    - 11.0.220.1/32
    - 11.0.221.1/32
    - 11.0.222.1/32
    - 11.0.223.1/32
    - 11.0.224.1/32
    - 11.0.225.1/32
    - 11.0.226.1/32
    - 11.0.227.1/32
    - 11.0.228.1/32
    - 11.0.229.1/32
    - 11.0.230.1/32
    - 11.0.231.1/32
    - 11.0.232.1/32
    - 11.0.233.1/32
    - 11.0.234.1/32
    - 11.0.235.1/32
    - 11.0.236.1/32
    - 11.0.237.1/32
    - 11.0.238.1/32
    - 11.0.239.1/32
    - 11.0.240.1/32
    - 11.0.241.1/32
    - 11.0.242.1/32
    - 11.0.243.1/32
    - 11.0.244.1/32
    - 11.0.245.1/32
    - 11.0.246.1/32
    - 11.0.247.1/32
    - 11.0.248.1/32
    - 11.0.249.1/32
  endpointSelector:
    matchLabels:
      app: noise
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: noise
  name: noise-pod
  namespace: world-repro
spec:
  containers:
  - image: k8s.gcr.io/pause:3.1
    name: pause
